### ISSUE TITLE
Internal labelled links in markdown are misparsed as hashtags

### ISSUE THREAD

**Issue by farooqkz** [deltachat/message-parser#66]
Input:
```
[internal link](#internal)
```
Expected output:
```
vec![LabeledLink {
    label: vec![Text("internal link")],
    destination: LinkDestination {
        target: "#internal",
        hostname: None,
        scheme: "",
        punycode: None,
    }
}]
```

Actual output:
```
vec![
    Text("[internal link]("),
    Tag("#intenal"),
    Text(")"),
]
```

**Comment by Simon-Laux** [comment]
you can not do internal/fragment/anchor links, where should they open to? they should not be parsed at all IMO. but not sure how we could achieve that in a nice way code wise.

**Comment by Simon-Laux** [comment]
I'd rather have them fail spectacularly than be falsely recognized... maybe we could say: if a valid labled link is detected, but contains a fragment instead of an url return the whole thing as text, that way it would not detect the hashtag.
But only return the stuff as text if the the link is a valid labeled fragment link.

another idea could be to discuss addition of labled hashtags, could also be a feature with some  smaller adjustement of a new element

**Comment by Simon-Laux** [comment]
Though a disadvantage to labeled hashtags could be that the the messages with those links would also appear int eh hashtag search results, as the hashtag is still part of the message and core does not do any special parsing when searching for them.

**Comment by farooqkz** [comment]
How about returning it as is?

**Comment by Simon-Laux** [comment]
> How about returning it as currently is?

what do you mean by "as currently is"?

**Comment by farooqkz** [comment]
> > How about returning it as currently is?
> 
> what do you mean by "as currently is"?

I mean as the current master parses them.

**Comment by Simon-Laux** [comment]
yes we could do that, but then wouldn't just text be better, I mean there was some reason you filed this issue.
Anyways I'm fine with both return as text and do as master currently returns it.

**Comment by farooqkz** [comment]
I also think probably it's better but I want more opinions. I'm reverting changes in the "Parse IRI" PR.
